//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SICE_BS_WEB.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IExpedienteComerciobinding", Namespace="http://tempuri.org/")]
    public partial class IExpedienteComercioservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPedimentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetzipOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcesadsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcesapecaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IExpedienteComercioservice() {
            this.Url = global::SICE_BS_WEB.Properties.Settings.Default.SICE_BS_WEB_WebReference_IExpedienteComercioservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPedimentoCompletedEventHandler GetPedimentoCompleted;
        
        /// <remarks/>
        public event GetzipCompletedEventHandler GetzipCompleted;
        
        /// <remarks/>
        public event ProcesadsCompletedEventHandler ProcesadsCompleted;
        
        /// <remarks/>
        public event ProcesapecaCompletedEventHandler ProcesapecaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ExpedienteComercioIntf-IExpedienteComercio#GetPedimento", RequestNamespace="urn:ExpedienteComercioIntf-IExpedienteComercio", ResponseNamespace="urn:ExpedienteComercioIntf-IExpedienteComercio")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TExpediente GetPedimento(string RFC, string Pedimento, string Tipo) {
            object[] results = this.Invoke("GetPedimento", new object[] {
                        RFC,
                        Pedimento,
                        Tipo});
            return ((TExpediente)(results[0]));
        }
        
        /// <remarks/>
        public void GetPedimentoAsync(string RFC, string Pedimento, string Tipo) {
            this.GetPedimentoAsync(RFC, Pedimento, Tipo, null);
        }
        
        /// <remarks/>
        public void GetPedimentoAsync(string RFC, string Pedimento, string Tipo, object userState) {
            if ((this.GetPedimentoOperationCompleted == null)) {
                this.GetPedimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPedimentoOperationCompleted);
            }
            this.InvokeAsync("GetPedimento", new object[] {
                        RFC,
                        Pedimento,
                        Tipo}, this.GetPedimentoOperationCompleted, userState);
        }
        
        private void OnGetPedimentoOperationCompleted(object arg) {
            if ((this.GetPedimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPedimentoCompleted(this, new GetPedimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ExpedienteComercioIntf-IExpedienteComercio#Getzip", RequestNamespace="urn:ExpedienteComercioIntf-IExpedienteComercio", ResponseNamespace="urn:ExpedienteComercioIntf-IExpedienteComercio")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TExpediente Getzip(string RFC, string pedimentoA) {
            object[] results = this.Invoke("Getzip", new object[] {
                        RFC,
                        pedimentoA});
            return ((TExpediente)(results[0]));
        }
        
        /// <remarks/>
        public void GetzipAsync(string RFC, string pedimentoA) {
            this.GetzipAsync(RFC, pedimentoA, null);
        }
        
        /// <remarks/>
        public void GetzipAsync(string RFC, string pedimentoA, object userState) {
            if ((this.GetzipOperationCompleted == null)) {
                this.GetzipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetzipOperationCompleted);
            }
            this.InvokeAsync("Getzip", new object[] {
                        RFC,
                        pedimentoA}, this.GetzipOperationCompleted, userState);
        }
        
        private void OnGetzipOperationCompleted(object arg) {
            if ((this.GetzipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetzipCompleted(this, new GetzipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ExpedienteComercioIntf-IExpedienteComercio#Procesads", RequestNamespace="urn:ExpedienteComercioIntf-IExpedienteComercio", ResponseNamespace="urn:ExpedienteComercioIntf-IExpedienteComercio")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TRespuesta Procesads(string Fkey, string RFC) {
            object[] results = this.Invoke("Procesads", new object[] {
                        Fkey,
                        RFC});
            return ((TRespuesta)(results[0]));
        }
        
        /// <remarks/>
        public void ProcesadsAsync(string Fkey, string RFC) {
            this.ProcesadsAsync(Fkey, RFC, null);
        }
        
        /// <remarks/>
        public void ProcesadsAsync(string Fkey, string RFC, object userState) {
            if ((this.ProcesadsOperationCompleted == null)) {
                this.ProcesadsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesadsOperationCompleted);
            }
            this.InvokeAsync("Procesads", new object[] {
                        Fkey,
                        RFC}, this.ProcesadsOperationCompleted, userState);
        }
        
        private void OnProcesadsOperationCompleted(object arg) {
            if ((this.ProcesadsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesadsCompleted(this, new ProcesadsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ExpedienteComercioIntf-IExpedienteComercio#Procesapeca", RequestNamespace="urn:ExpedienteComercioIntf-IExpedienteComercio", ResponseNamespace="urn:ExpedienteComercioIntf-IExpedienteComercio")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TRespuesta Procesapeca(string Fkey, string RFC) {
            object[] results = this.Invoke("Procesapeca", new object[] {
                        Fkey,
                        RFC});
            return ((TRespuesta)(results[0]));
        }
        
        /// <remarks/>
        public void ProcesapecaAsync(string Fkey, string RFC) {
            this.ProcesapecaAsync(Fkey, RFC, null);
        }
        
        /// <remarks/>
        public void ProcesapecaAsync(string Fkey, string RFC, object userState) {
            if ((this.ProcesapecaOperationCompleted == null)) {
                this.ProcesapecaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesapecaOperationCompleted);
            }
            this.InvokeAsync("Procesapeca", new object[] {
                        Fkey,
                        RFC}, this.ProcesapecaOperationCompleted, userState);
        }
        
        private void OnProcesapecaOperationCompleted(object arg) {
            if ((this.ProcesapecaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesapecaCompleted(this, new ProcesapecaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ExpedienteComercioIntf")]
    public partial class TExpediente {
        
        private string pedimentoField;
        
        private string archivoField;
        
        private string rFCField;
        
        private string tipoField;
        
        /// <remarks/>
        public string Pedimento {
            get {
                return this.pedimentoField;
            }
            set {
                this.pedimentoField = value;
            }
        }
        
        /// <remarks/>
        public string Archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ExpedienteComercioIntf")]
    public partial class TRespuesta {
        
        private string fkeyField;
        
        private string rFCDSField;
        
        private string errorField;
        
        /// <remarks/>
        public string Fkey {
            get {
                return this.fkeyField;
            }
            set {
                this.fkeyField = value;
            }
        }
        
        /// <remarks/>
        public string RFCDS {
            get {
                return this.rFCDSField;
            }
            set {
                this.rFCDSField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetPedimentoCompletedEventHandler(object sender, GetPedimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPedimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPedimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TExpediente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TExpediente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetzipCompletedEventHandler(object sender, GetzipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetzipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetzipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TExpediente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TExpediente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ProcesadsCompletedEventHandler(object sender, ProcesadsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcesadsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcesadsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TRespuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRespuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ProcesapecaCompletedEventHandler(object sender, ProcesapecaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcesapecaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcesapecaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TRespuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRespuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591